### ISSUE TITLE
Using multiple classes for tag shortcut

### ISSUE THREAD

**Issue by samuelduda** [apptoix/bracketstoix#12]
Currently only one class can be processed.
`d#myId.foo` -› `<div id="myId" class="foo"></div>`

Approach for passing multiple classes
`d#myId.foo.bar` -› `<div id="myId" class="foo bar"></div>`

**Comment by apptoix** [comment]
Hi, Samuel
I have just updated the new version of BracketstoIX. 
The tag command supports multiple classes.
