### ISSUE TITLE
TypoScript *.txt file: UPPERCASE on save

### ISSUE THREAD

**Issue by GuidoJansen** [apptoix/bracketstoix#14]
I'm having this issue which might be introduced with the latest update (V2.11.0).

I'm having a TXT-File with a TypoScript content. This is a case sensitive format.
When I save that document brackets converted the document in all UPPERCASE.

After I uninstalled BracketstoIX that behavior was gone.
After I reinstalled BracketstoIX that behavior was reintroduced.

Brackets Version
Release 1.1 Build 1.1.0-15558 (release ea908cae5) 

Other Brackets extensions I have installed
* Command Line Shortcuts 0.2.1
* recognizer 0.0.9
* Autoprefixer 0.5.20
* Beautify 1.1.6	
* Brackets Compare 0.0.1	
* Brackets Git 0.14.14
* Brackets Icons 1.3.0	
* Brackets Working File Tabs 1.0.3	
* brackets-add-comment 0.1.2	
* Code Folding 0.3.1
* Column Ruler 2.3.6
* Emmet 1.2.0
* Extract for Brackets (Preview) 0.6.1-1719-release
* File System Properties 1.0.1
* FunctionFinder 1.0.0
* HTML Block Selector 1.0.1
* Inline Regex Editor 1.1.3
* Integrated Development 0.5.59
* JSCS 0.2.0
* JSDownloader 3.1.0
* JSHint 2.2.10
* Markdown Preview 1.0.10
* More CSS Code Hints 1.0.2
* Node.js bindings 1.4.0
* PHP Syntax Hint 1.1.3
* PHPLint for Brackets 1.0.2
* QuickDocsPHP 1.4.7
* Rename JavaScript Identifier 0.2.8
* Resizable Bottom Working Files 1.0.1
* Theseus for Brackets 0.4.19
* Toolbar Toggle 1.0.0
* W3CValidation 2.1.6
* WD Minimap 2.2.3
* Whitespace Normalizer 0.3.0
* WordHint 1.0.2

**Comment by apptoix** [comment]
Hi. 
Thank you for the feedback.
I found the bug and fixed.
Just release a new version with that problem solved.
Sorry for the inconvenience.

**Comment by GuidoJansen** [comment]
Got the new version.
Problem solved at my place.

**Comment by konstantin83** [comment]
Is there a possibility to highlight TypoScript code in Brackets? COuldn't find an extension for that...

**Comment by apptoix** [comment]
Hi. Sorry, about the delayed answer.
Syntax Highlighting is outside the scope of this extension, sorry.
It's true there is no typoscript syntax highlighting, at least I didn't found it , only typescript but it's something completely different.

**Comment by konstantin83** [comment]
Ok thank you for you answer
